language: r
sudo: true
cache:
 - packages
 - "/tmp/texlive"
 - "/$HOME/.texlive"
warnings_are_errors: false
before_install:
 - bash ./ci/setlocale.sh
 - source ./ci/installtexlive.sh
 - tlmgr install acronym bigfoot blindtext chngcntr cmap nowidow mdframed navigator needspace tablefootnote tocloft xpatch
 - tlmgr update --all
 - sudo apt-get update
 - sudo apt-get install texlive-bibtex-extra
install: echo Installation step
before_script:
 # as somehow no biber package is available for ubuntu 12.04 via apt, let's just download it directly
 - wget "https://sourceforge.net/projects/biblatex-biber/files/biblatex-biber/current/binaries/Linux/biber-linux_x86_64.tar.gz"
 - tar xzf biber-linux_x86_64.tar.gz
 - export PATH=$PATH:$PWD
 - tlmgr update biber
 - bash ./ci/replaceumlaute.sh
script: 
 - xelatex main.tex
 - xelatex main.tex
 - biber main
 - xelatex main.tex
 - xelatex main.tex
deploy:
 provider: releases
 api_key:
   secure: uWMQ2Ad+1YYGLLDIKmGV3vH6cIaU8xaeAbd8QfmRetnicjXqZZXJOSKy2lxzrTSeI4Dta/28T4jmH/Ef4X8wiRjxkysWP32Jw6fMPGLL8hracY2Qz82Myfnj+ue5lTpS1dZ8RJ9PY7r4+rxV8QO4Ntdzs4uN/bYW9yPrSt1eN9aHziKM/pO6jw+QGzcqWjNvvOJRi8RBdUDTT6HBZYXVKGbJ3QBnTQiVUC55lO7Iq6jAOqUYnMJPGeDtE9LoqrlAGTH9lujxZuHAJQCQa6H8Sf7PY74Xlig1OH9+q56JM6GKoK7YLuPUK//Xw/4Wq++MaolVklb53saojW3YuFcfZa4reP1W4ltUjmO2ZiUzxzst+k9QD+I2r5oXHB381FOArAr7mpBDrcKQvAC5X8IkGfgYkGSoH3N50d7KAP0PeVc3ttGKdoxqaY0BWqtda2tB0zf1ZfoZV4LpkJhjlRFsQOS7w75SA/aTeyL3+s80dQ5StedqqwMgnpuxUz8ab1Mxf3W8iz9HVVN7i/xH7X8wTi9mEWARC+TMjSsb5da5zjOZMK2r8VfpBY5+YmkxWKJZXqbzokHzVN1zY266msHJDm71hYsMkgnJQeTiFysFOOf7Kz7O0kjZizw/6U2SFxtDQoUDn2VP5dG2QSuA21gv3lTg/vLJMjQYIn5qc0xCy/A=
 file: main.pdf
 skip_cleanup: true
 on:
  repo: stefreschke/Report-Template
notifications:
  email: false
